@BankAccountManagerApiHostAddress=https://localhost:7002

### -------------------- Account --------------------

GET {{BankAccountManagerApiHostAddress}}/account
Accept: application/json

###

POST {{BankAccountManagerApiHostAddress}}/account
Content-Type: application/json

{
    "accountNumber": "7068/00059-0",
    "accountHolder": "341 - Banco Itaú",
    "description": "Poupança"
}
###
### -------------------- Transaction --------------------

GET {{BankAccountManagerApiHostAddress}}/transaction?accountId=1&startTransactionDate=2024-06-01
Accept: application/json

###

POST {{BankAccountManagerApiHostAddress}}/transaction
Content-Type: application/json

[
  {
    "accountId": 1,
    "amount": 25,
    "transactionDate": "2024-06-03T00:00:00Z",
    "description": "Balada",
    "capitalizationEvent": false,
    "transferenceBetweenAccounts": false,
    "transactionAmountType": 0
  }
]
###

DELETE {{BankAccountManagerApiHostAddress}}/transaction?accountId=1&transactionId=2
Accept: application/json


### -------------------- Transaction Type --------------------

###
GET {{BankAccountManagerApiHostAddress}}/transaction-type
Accept: application/json

###
POST {{BankAccountManagerApiHostAddress}}/transaction-type
Content-Type: application/json

{
    "transactionTypeString": "PlanoSaude"
}
###

PUT {{BankAccountManagerApiHostAddress}}/transaction-type/5
Content-Type: application/json

{
    "transactionTypeString": "Plano Saúde"
}
###